# Generated by Django 4.0.2 on 2022-05-06 10:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bio', models.CharField(max_length=160)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profiles_avatar/')),
                ('connected_profiles', models.ManyToManyField(blank=True, to='BarkerApp.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('reciver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recived_by', to='BarkerApp.profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sended_by', to='BarkerApp.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Bark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=280)),
                ('media', models.ImageField(blank=True, null=True, upload_to='barks_media/')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BarkerApp.profile')),
                ('replies', models.ManyToManyField(blank=True, to='BarkerApp.Bark')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_bark', to='BarkerApp.bark')),
            ],
        ),
    ]
