# Generated by Django 4.0.2 on 2022-05-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarkerApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bark',
            name='author',
        ),
        migrations.AddField(
            model_name='profile',
            name='barks',
            field=models.ManyToManyField(blank=True, to='BarkerApp.Bark'),
        ),
    ]
