# Generated by Django 4.0.2 on 2022-05-11 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BarkerApp', '0002_remove_bark_author_profile_barks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='barks',
        ),
        migrations.AddField(
            model_name='bark',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BarkerApp.profile'),
        ),
    ]
