# Generated by Django 4.0.2 on 2022-03-10 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BarkerApp', '0002_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='connected_profiles',
            field=models.ManyToManyField(to='BarkerApp.Profile'),
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('reciver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recived_by', to='BarkerApp.profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sended_by', to='BarkerApp.profile')),
            ],
        ),
    ]
