# Generated by Django 4.0.2 on 2022-03-10 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BarkerApp', '0005_alter_profile_connected_profiles_bark'),
    ]

    operations = [
        migrations.AddField(
            model_name='bark',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BarkerApp.profile'),
        ),
    ]
