# Generated by Django 4.0.2 on 2022-03-10 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarkerApp', '0006_bark_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bark',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='bark',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='request',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
