# Generated by Django 4.0.2 on 2022-03-15 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BarkerApp', '0007_alter_bark_date_alter_bark_media_alter_request_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bark',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to='bark_media/'),
        ),
        migrations.AlterField(
            model_name='bark',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_bark', to='BarkerApp.bark'),
        ),
    ]
