# Generated by Django 4.0.2 on 2022-03-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarkerApp', '0008_alter_bark_media_alter_bark_reply_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bark',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to='barks_media/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profiles_avatar/'),
        ),
    ]
